version: '3'

tasks:
  dev:
    cmds:
      - uv run uvicorn app.main:app --reload

  test:
    deps: [test:frontend, test:backend]

  test:frontend:
    cmds:
      - /opt/homebrew/bin/deno run static/run-tests.js

  test:backend:
    cmds:
      - uv run pytest app/ || test $? -eq 5
